# To run the build from the package root:
#    docker buildx build --platform linux/amd64,linux/arm64 -f ./docker-build/Dockerfile.custom -t "breezy-kwin-custom" .
#    docker run --rm -t -v ./:/source -v --platform linux/amd64 "breezy-kwin-custom:amd64"
#    docker run --rm -t -v ./:/source -v --platform linux/arm64 "breezy-kwin-custom:arm64"

FROM archlinux:latest

RUN echo "Server = https://archive.archlinux.org/repos/2023/02/01/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
RUN echo "SigLevel = Never" >> /etc/pacman.conf

RUN pacman -Sy --noconfirm --needed --nodeps \
    ca-certificates \
    base-devel \
    cmake \
    pkgconf \
    git \
    curl \
    wget \
    extra-cmake-modules \
    qt5-base \
    qt5-declarative \
    qt5-tools \
    kconfig \
    kconfigwidgets \
    kcoreaddons \
    kglobalaccel \
    ki18n \
    kcmutils \
    kxmlgui \
    kwindowsystem \
    kwin \
 && pacman -Scc --noconfirm

WORKDIR /source

CMD bin/package_kwin_plugin
