name: Package KWin Plugin

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build Docker image
        run: sudo docker buildx build --platform linux/amd64 -f ./kwin/docker-build/Dockerfile -t "breezy-kwin" .

      - name: Package KWin plugin
        run: sudo docker run --rm -t -v ${{ github.workspace }}:/source -w /source/kwin --platform linux/amd64 "breezy-kwin" bin/package_kwin_plugin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: breezy-kwin-plugin
          path: kwin/out/breezyKWinPlugin-x86_64.tar.gz
